on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/*'
      - Dockerfile
      - '*.go'
      - '*.mod'
      - '*.sum'
      - '**/*_test.go'
  pull_request:
    paths:
      - '.forgejo/workflows/*'
      - Dockerfile
      - '*.go'
      - '*.mod'
      - '*.sum'
      - '**/*_test.go'

env:
  IMAGE_SLUG: ${{ vars.FORGEJO_HOST }}/${{ forgejo.repository }}

jobs:
  test:
    runs-on: docker
    container:
      image: golang:1.24-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...

  docker-build-and-push:
    runs-on: docker
    needs: test
    if: forgejo.event_name == 'push' && forgejo.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lowercase Docker image name
        id: image_string
        uses: https://github.com/ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_SLUG }}
      - name: Docker login
        uses: https://github.com/docker/login-action@v3
        with:
          registry: ${{ vars.FORGEJO_HOST }}
          username: ${{ forgejo.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Docker build
        run: docker build -t ${{ steps.image_string.outputs.lowercase }}:${{ forgejo.sha }} .
      - name: Docker push SHA-tagged
        run: docker push ${{ steps.image_string.outputs.lowercase }}:${{ forgejo.sha }}
